version: "3"
services:
    web:
        build: .
        ports:
            - "5000:5000"
            - "5001:5001"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"