export const ADD_NOTE = 'ADD_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const SELECT_NOTE = 'SELECT_NOTE';
export const TOGGLE_DELETE_BUTTON = 'TOGGLE_DELETE_BUTTON';
export const GET_NOTES = 'GET_NOTES';
// export const TOGGLE_VISIBILITY_NOTE = 'TOGGLE_VISIBILITY_NOTE';